---

- name: Updating aliases!
  hosts: all
  become: true
  remote_user: brandon
  

  tasks:

    - name: add new aliases
      lineinfile:
        path: /home/brandon/.bashrc
        line: alias a='bash /home/brandon/scripts/selektor.sh'
        line: alias ..="cd .."
        line: alias ...="cd ../.."
        line: alias hosts="sudo nano /etc/hosts"


    - name: source bashrc file    
      shell: . ~/.bashrc 
      

      

     
