---

- name: simple upgrade / update / cleaning for all systems
  hosts: network
  become: true
  remote_user: brandon
  

  tasks:

    - name: run initial apt update / upgrade
      become: true
      apt:
        upgrade: full
        update_cache: true
        autoclean: true
        autoremove: true	



      

     
