---

- name: welcome wagon for new VMs
  hosts: ramiel
  become: true
  remote_user: brandon
  

  tasks:

    - name: run initial apt update / upgrade
      become: true
      apt:
        upgrade: full
        update_cache: true

    - name: install apps
      apt:
        name: 
          - nmap
          - neofetch
          - python3
          - python3-pip 
          - htop
          - git
        state: present
        update_cache: true
      
    - name: copy selektor menu shell script
      copy:
        src: ~/playbooks/selektor.sh
        dest: /home/brandon/scripts/
        owner: brandon
        group: brandon
        mode: 0420


    - name: copy copland.txt ascii art
      copy:
        src: ~/playbooks/copland.txt
        dest: /home/brandon/scripts/
        owner: brandon
        group: brandon
        mode: 0420


    - name: add quickmenu alias
      lineinfile:
        path=/home/brandon/.bashrc
        line="alias a='bash /home/brandon/scripts/selektor.sh'"
        owner=brandon
       

    - name: source bashrc   
      shell: . /home/brandon/.bashrc && uptime


    - name: add update / upgrade cron jobs
      cron:
        name: update / upgrade
        user: "brandon"
        minute: 00
        hour: 00
        job: "sudo apt update ; sudo apt upgrade -y"
      become: yes




      

     
